### ISSUE TITLE
missing commit error in matlab

### ISSUE THREAD

**Issue by mzaiss** [kherz/pulseq-cest#1]
![grafik](https://user-images.githubusercontent.com/8328474/103347729-16076580-4a98-11eb-80b7-2dafff49ab6f.png)

as soon as I installed it and make a right click to a seq file of the library in Matlab I get this weird error message which block the context menue

**Comment by kherz** [comment]
It's because we clone with depth 1, but thats weird...
if I change line 29  from
        sys_cmd = ['git clone --depth 1 https://github.com/kherz/pulseq-cest-library.git ' lib_path];
to 
        sys_cmd = ['git clone https://github.com/kherz/pulseq-cest-library.git ' lib_path];
the error disappears
