### ISSUE TITLE
Additions to the documentation

### ISSUE THREAD

**Issue by lukas-k** [kherz/pulseq-cest#5]
Dear all,

I have sucessfully tested the pulseq-cest / pypulseq-cest package. Thank you for providing this elaborate module. There are a few aspects that could be improved / added to the documentation:

## Environment
Python-version of the pulseq-cest project. Hence, application-specific questions refer to the python version.

Windows 10, Anaconda with separate environment having Python 3.9.2 installed

Other relevant python packages:
BMCTool            0.3.1 (pip)
pypulseq           1.3.1.post1 (pip)

## Feedback
1. Overview simulation algorithms / equations / particularities
-> Overview required to assess the quality of results, being able to read / decode the m_out vector (ordering of dimensions, pools, ...), ...
It would be great to have a chart / documentation page which explains:

    a. The equations being simulated describing the spin dynamics (BMC)

    b. How the vectors / matrices are organized Mx(H2O), Mx(CEST1), -> Ideally use same symbols as in C++ source code for reference.

    c. How are the .yaml files organized? What is the effect of the parameters? What ordering and which units are expected? --> Can also reference to the GM example which answers those questions

    d. Which pulseq-Sequence blocks are interpreted and how? -> RF fully (on sample-level (re-sampled to piecewise constant functions for faster performance) ), ADC as snapshot of magnetization vector (until storage is full), GX==TRAP && GY==TRAP && GZ==TRAP -> Spoiler -> Clear Mx/My of all CEST + MT pools, Other (Gradient, Delay) as undriven precession

    e. Maybe short overview of Pade approximation / iterative solver (updateBlochMatrix, solve)
This documentation page could be located on the github.io Documentation site and/or inside a README (which one?)

**Comment by kherz** [comment]
Hi Lukas,
thanks for your detailed feedback. I will definitely come back to this when adding more documentation.
b) and c) are partly covered in the pulseq-cest-sim/readme, however, this was written before we switched to yaml-files.

**Comment by kherz** [comment]
After some restructuring and refactoring, this should now be partially covered in the readmes.

*b. How the vectors / matrices are organized Mx(H2O), Mx(CEST1), -> Ideally use same symbols as in C++ source code for reference.*
https://github.com/kherz/pulseq-cest/tree/master/pulseq-cest-sim#magnetization-vector

*c. How are the .yaml files organized? What is the effect of the parameters? What ordering and which units are expected? --> Can also reference to the GM example which answers those questions*
https://github.com/kherz/pulseq-cest/tree/master/examples#yaml-parameter-files

*d. Which pulseq-Sequence blocks are interpreted and how? -> RF fully (on sample-level (re-sampled to piecewise constant functions for faster performance) ), ADC as snapshot of magnetization vector (until storage is full), GX==TRAP && GY==TRAP && GZ==TRAP -> Spoiler -> Clear Mx/My of all CEST + MT pools, Other (Gradient, Delay) as undriven precession*
https://github.com/kherz/pulseq-cest/tree/master/seq-generation#saturation-pulses

a) and e) are imo too specific too be covered in the Readmes, but might be included in a larger Documentation on the github.io page 

Feel free to close this issue or add more documentation requests.
